apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: Ym9vay1yZHMuYzU2d2c0bzR3ZDc4LnVzLXdlc3QtMi5yZHMuYW1hem9uYXdzLmNvbQ==
  db_username: YWRtaW4=
  db_password: c3JpdmFyZGhhbg==
